config/routes.rb
Rails.application.routes.draw do
  get 'site/index'

  get 'site/about'

  get 'site/contact'

  #The following lines were created when we created the controllers
  #get 'order_items/create'
  #get 'order_items/update'
  #get 'order_items/destroy'
  #get 'carts/show'
  #get 'products/index'
  
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  #Display Men's Products as linked to from _navigation.html.erb:
  get '/men' => 'products#men'

  #Display Women's Products as linked to from _navigation.html.erb:
  get '/women' => 'products#women'
  
  #Display Purchase Confirmation Message from _navigation.html.erb:
  get '/checkout' => 'carts#checkout'

  mount Upmin::Engine => '/admin'
  #The line below is the original reference from the Devise intall
  #root to: 'visitors#index'
  root to: "site#index"
  devise_for :users
  resources :users
end

app/models/_product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    #This is where the cart order item price is calculated based on the quantity selected as can be seen by the old line of code below
    #order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
    order_items.collect { |oi| oi.valid? ? (oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  # The following line confirms that a quantity has been choosen. Removing it limits the order quantity to 1
  # validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    #if persisted?
    #  self[:unit_price]
    #else
      product.price
    #end
  end

  def total_price
    unit_price #* quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    #self[:unit_price] = unit_price
    #self[:total_price] = quantity * self[:unit_price]
    unit_price
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @order_items = current_order.order_items
  end
  
  # Dummy Checkout Page
  def checkout
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
  
#Check this later for the cart quantity number
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  
  def men
    @products = Product.where(Category: "Men")
    @order_item = current_order.order_items.new
    render 'products/index'
  end
  
  def women
    @products = Product.where(Category: "Women")
    @order_item = current_order.order_items.new
    render 'products/index'
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
      <%# Display Images and Product Model %>
      <%= image_tag product.thumburl, :style => "height:100px"%>
      <p><%= product.model %></p>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency(order_item.unit_price, :unit => "€") %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%#= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%#= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency(order_item.total_price, :unit => "€") %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

<%#= Continue Shopping and Checkout Buttons %>
<div class="col-xs-8 text-right">
  <div class="btn-group">
    <%= link_to 'Continue Shopping', root_path, class: "btn btn-primary" %>  
  </div>
  <div class="btn-group">
    <%= link_to "Checkout Now", checkout_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/carts/checkout.html.erb
<h1>Checkout</h1>
<%= link_to "Your order of #{current_order.order_items.size} Items, valued at #{number_to_currency current_order.subtotal}, has been processed and will be shipped shortly", cart_path, class: "btn btn-link" %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency(current_order.subtotal, :unit => "€")} )", cart_path, class: "btn btn-link" %>
<%# Link to Checkout View %>
<%= link_to "Checkout Now", checkout_path, class: "btn btn-link" %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', site_index_path, class: 'navbar-brand' %>
      <%= link_to 'Shop', products_path, class: 'navbar-brand' %>
      <%= link_to 'About Us', site_about_path, class: 'navbar-brand' %>
      <%= link_to 'Contact', site_contact_path, class: 'navbar-brand' %>
      
      <%# Links to filter products by gender %>
      <%= link_to 'Men', men_path, class: 'navbar-brand' %>
      <%= link_to 'Women', women_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to current_user.email, edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Register', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.1.erb
<!DOCTYPE html>
<html>
  <head>
    <!--<title>Súillin Opticians</title> CHECK THIS LATER-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Suillin Opticians" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Suillin Opticians" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "Eyeware", root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>

<!--
  THIS CODE MAY NO LONGER BE NECESSARY TO SUPPORT BOOTSTRAP AS WE HAVE INSTALLED BOOTSTRAP IN RAILS
  
  <#%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <#% if request.ssl? %>
    <#%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <#%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <#% else %> 
    <#%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <#%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <#% end %>
  <#%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <#%= csrf_meta_tags %>

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--<title>Súillin Opticians</title> CHECK THIS LATER-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Suillin Opticians" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Suillin Opticians" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="container">
    <div class="row">
      
      	<div>
					<img src="assets/logo.png" alt="Súillin Opticians Logo" width="330px"/>
				</div>
      <div class="col-xs-6">
        <!--<h1><%= link_to "Eyeware", root_path %></h1> -->
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
      <%# Display Images and Product Model %>
      <%= image_tag product.thumburl %>
      <p><%= product.model %></p>
      <p><%= product.description %></p>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency(product.price, :unit => "€") %></span></h4>
        <div class="input-group">
          <!-- Removing the following line removes the quantity selection box from the store front, some of this other html code is no longer needed and can be removed later -->
          <%#= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          
          <div class="input-group-btn">
            <%if signed_in?%>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary right" %>
             <%end%>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>